name: Go Test

on: [push, pull_request]

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Setup Go
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: 1.x
  #   - name: Run tests
  #     run: make run-all-tests-verbose

  test-container:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      mydb:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
        # volumes: -- cd.. ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql
    steps:
    - name: Verify MySQL connection from container 
      run: |
        apt-get update
        apt-get install -y mysql-client
        mysql --host mydb -uroot -ppassword -e "SHOW DATABASES"